name: planktonsdm-env
channels:
  - defaults
  - conda-forge
dependencies:
  - cartopy
  - libgdal
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyyaml
  - seaborn
  - xarray
  - xgboost
  - ipykernel
  - scikit-learn
  - scipy