[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "planktonsdm"
version = "0.0.8"
authors = [
  { name="nanophyto", email="joost.devries@bristol.ac.uk" },
]

description = "A package to build plankton species distribution models"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/nanophyto/planktonSDM"

[tool.hatch.build]
exclude = [
  "/.git",
  "/singularity",
  "/data",
]



