---
  local_root: /home/phyto/CoccoML/
  remote_root: /user/work/ba18321/planktonSDM/

  path_out: predictions/merged/
  path_in: predictions/ENS/
  traits: data/traits.csv
  training: data/abundances_environment.csv

  scale_X: True 

  predictors: ['mld', 'irradiance', 'din', 'phosphate', 'chlor_a', 'si', 'temperature', 'DIC', 'o2']
  verbose: 1
  seed : 1 # random seed
  n_threads : 2 # how many cpu threads to use
  cv : 3
  
  ensemble_config: 
    rf: zir
    xgb: zir
    knn: zir

  clf_scoring:
   accuracy: balanced_accuracy

  reg_scoring:
   R2: r2
   MAE: neg_mean_absolute_error
   RMSE: neg_root_mean_squared_error

  local_param_grid:
    rf_param_grid:
      reg_param_grid:
        regressor__n_estimators: [100]
        regressor__max_features: [2, 3, 4]
        regressor__max_depth: [3, 5]
        regressor__min_samples_leaf: [0.2, 0.5]
        regressor__max_samples: [0.2, 0.5]     
      clf_param_grid:
        n_estimators: [100]
        max_features: [2, 3, 4]
        max_depth: [3, 5]
        min_samples_leaf: [0.2, 0.5]
        max_samples: [0.5]   

    xgb_param_grid:
      clf_param_grid:  
        eta: [0.01]
        n_estimators: [100]
        max_depth: [4]
        subsample: [0.6]  
        colsample_bytree: [0.6]
        gamma: [1] 
        alpha: [1]   
      reg_param_grid:  
        regressor__eta: [0.01]
        regressor__n_estimators: [100]
        regressor__max_depth: [4]
        regressor__subsample: [0.6]  
        regressor__colsample_bytree: [0.6]
        regressor__gamma: [1] 
        regressor__alpha: [1]   

    knn_param_grid:
      clf_param_grid:  
        max_samples: [0.5]
        max_features: [0.5]
        estimator__leaf_size: [30]
        estimator__n_neighbors: [3]
        estimator__p:  [1]           
        estimator__weights: ["uniform"]
      reg_param_grid:  
        regressor__max_samples: [0.5]
        regressor__max_features: [0.5]
        regressor__estimator__leaf_size: [30]
        regressor__estimator__n_neighbors: [3]
        regressor__estimator__p:  [1]           
        regressor__estimator__weights: ["uniform"]

  remote_param_grid:
    rf_param_grid:
      reg_param_grid:
        regressor__n_estimators: [250]
        regressor__max_features:  ['sqrt', 1, 2, 4, 6, 8, 10]
        regressor__max_depth: [2, 26, 51, 75, 100, None]
        regressor__min_samples_leaf: [1, 5, 13, 25, 37, 50]
        regressor__max_samples: [0.2, 0.3, 0.5, 0.6, 0.7, 0.8, 1]     
      clf_param_grid:
        n_estimators: [250]
        max_features:  ['sqrt', 1, 2, 4, 6, 8, 10]
        max_depth: [2, 26, 51, 75, 100, None]
        min_samples_leaf: [1, 5, 13, 25, 37, 50]
        max_samples: [0.2, 0.3, 0.5, 0.6, 0.7, 0.8, 1]  

    xgb_param_grid:
      clf_param_grid:  
        eta: [0.01, 0.015, 0.025, 0.05, 0.1]
        n_estimators: [100]
        max_depth: [3, 6, 8, 12, 16, 25]
        subsample: [0.4, 0.6, 0.7, 0.8, 1]
        colsample_bytree: [0.083, 0.1667, 0.33, 0.5, 0.667, 0.8, 0.9, 1]
        gamma: [0] 
        alpha: [0, 0.1]
      reg_param_grid:  
        regressor__eta: [0.01, 0.015, 0.025, 0.05, 0.1]
        regressor__n_estimators: [100]
        regressor__max_depth: [3, 6, 8, 12, 16, 25]
        regressor__subsample: [0.4, 0.6, 0.7, 0.8, 1]
        regressor__colsample_bytree: [0.083, 0.1667, 0.33, 0.5, 0.667, 0.8, 0.9, 1]
        regressor__gamma: [0] 
        regressor__alpha: [0, 0.1]

    knn_param_grid:
      clf_param_grid:  
        max_samples: [0.2, 0.4, 0.6, 0.8, 1]
        max_features: [0.2, 0.4, 0.6, 0.8, 1]
        estimator__leaf_size: [30]
        estimator__n_neighbors: [5, 8, 10, 12, 16 ,21]
        estimator__p:  [1,2]       
        estimator__weights: ["uniform", "distance"]
      reg_param_grid:  
        regressor__max_samples: [0.2, 0.4, 0.6, 0.8, 1]
        regressor__max_features: [0.2, 0.4, 0.6, 0.8, 1]
        regressor__estimator__leaf_size: [30]
        regressor__estimator__n_neighbors: [5, 8, 10, 12, 16 ,21]
        regressor__estimator__p:  [1,2]        
        regressor__estimator__weights: ["uniform", "distance"]
  

  knn_bagging_estimators: 30

