---
  root: /home/phyto/CoccoML/

  path_out: ModelOutput/
#  path_in: predictions/ENS/
#  path_in: predictions/ENS/

  traits: /home/phyto/CoccoML/data/traits.csv
  
  scale_X: True

  verbose: 1
  seed : 1 # random seed
  n_threads : 2 # how many cpu threads to use
  cv : 3
  predict_probability: False 

  ensemble_config: 
    m1: 
      model : "rf"
      regressor : False
      classifier : True
    # m2: 
    #   model : "xgb"
    #   regressor : False
    #   classifier : True      
  upsample: False
  clf_scoring:
   accuracy: balanced_accuracy

  reg_scoring:
   R2: r2
   MAE: neg_mean_absolute_error
   RMSE: neg_root_mean_squared_error

  param_grid:
    rf_param_grid:
      reg_param_grid:
        regressor__n_estimators: [100]
        regressor__max_features: [3, 4]
        regressor__max_depth: [50, 100]
        regressor__min_samples_leaf: [ 0.5, 1]
        regressor__max_samples: [0.5, 1]     
      clf_param_grid:
        n_estimators: [100]
        max_features: [3, 4]
        max_depth: [50, 100]
        min_samples_leaf: [0.5, 1]
        max_samples: [0.5, 1]   

    xgb_param_grid:
      clf_param_grid:  
        eta: [0.01]
        n_estimators: [100]
        max_depth: [4]
        subsample: [0.6]  
        colsample_bytree: [0.6]
        gamma: [1] 
        alpha: [1]   
      reg_param_grid:  
        regressor__eta: [0.01]
        regressor__n_estimators: [100]
        regressor__max_depth: [4]
        regressor__subsample: [0.6]  
        regressor__colsample_bytree: [0.6]
        regressor__gamma: [1] 
        regressor__alpha: [1]   

    knn_param_grid:
      clf_param_grid:  
        max_samples: [0.5]
        max_features: [0.5]
        estimator__leaf_size: [30]
        estimator__n_neighbors: [3]
        estimator__p:  [1]           
        estimator__weights: ["uniform"]
      reg_param_grid:  
        regressor__max_samples: [0.5]
        regressor__max_features: [0.5]
        regressor__estimator__leaf_size: [30]
        regressor__estimator__n_neighbors: [3]
        regressor__estimator__p:  [1]           
        regressor__estimator__weights: ["uniform"]

  knn_bagging_estimators: 30

